language: perl
os:
  - linux
  # - osx

perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.16"
  - "5.14"
  # - "5.12"
  - "5.24-shrplib"

matrix:
  allow_features:
    - perl: blead
  include:
    - perl: 5.28
      env: COVERAGE=1

sudo: false

before_script:
  - coverage-setup

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - cpanm -n File::Fetch

install:
  - cpan-install --deps
  - cpan-install --coverage
  - cpanm -n Devel::Cover::Report::Coveralls Locale::Country Test::Pod::Spelling::CommonMistakes FCGI::Buffer Log::WarnDie

script:
  # perl Makefile.PL && make && cover -test -report coveralls
  - perl Makefile.PL && make && prove -l -j$(test-jobs) $(test-files)

after_success:
  - coverage-report
